package com.example.fittestbot.model;

public enum Operation {
  NONE,
  REGISTER_NAME,
  REGISTER_SURNAME,
  REGISTER_GROUP,
  REGISTER_TEST_NAME,
  REGISTER_TEST_QUESTION,
  REGISTER_TEST_ANSWERS,
  TEST_CHOOSING,
  TEST_PROCESSING,
  DELETING_TEST
}
